version: "3.8"

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./requirements/wp_volume/server.crt:/etc/nginx/ssl/server.crt:ro
      - ./requirements/wp_volume/server.key:/etc/nginx/ssl/server.key:ro
      - wordPress:/var/www/html
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    env_file:
      - .env
    ports:
      - 9000:9000
    volumes:
      - wordPress:/var/www/html
  db:
    build: ./requirements/mariadb
    container_name: db
    env_file:
      - .env
    ports:
      - 3306:3306
    volumes:
      - DB:/var/lib/mysql
  
volumes:
  wordPress:
  DB: